CREATE TABLE `sys_role` (
  `role_id` BIGINT(32) AUTO_INCREMENT,
  `role_name` VARCHAR(32) DEFAULT NULL COMMENT '角色名称',
  `role_memo` VARCHAR(128) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`role_id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;